# Matrices

In [1]:
import numpy as np 
A = np.array([[10, 95, 8], [95, 20, 9], [8, 9, 30]])
B  = np.array([[5, 8, 3, 6], [ 95, 20, 9, 3], [ 8, 9, 30, 3], [8, 9, 30, 3]])
C = np.array([[0, 6, 250 ], [-6, 0, 86.3], [-250, -86.3, 0]])

type_A = type(A)
type_B = type(B)
type_C = type(C)

print(" A, B and C are matrices of type {}, {}, {}".format(type_A, type_B, type_C))

 A, B and C are matrices of type <class 'numpy.ndarray'>, <class 'numpy.ndarray'>, <class 'numpy.ndarray'>


## Transpose A, B and C

In [2]:
# transpose of the matrices
A_T = np.transpose(A)
B_T = np.transpose(B)
C_T = np.transpose(C)
print("A transpose is  \n {}".format(A_T)) 
print("B transpose is \n {}".format(B_T)) 
print("C transpose is \n {}".format(C_T)) 

A transpose is  
 [[10 95  8]
 [95 20  9]
 [ 8  9 30]]
B transpose is 
 [[ 5 95  8  8]
 [ 8 20  9  9]
 [ 3  9 30 30]
 [ 6  3  3  3]]
C transpose is 
 [[   0.    -6.  -250. ]
 [   6.     0.   -86.3]
 [ 250.    86.3    0. ]]


Let us check each matrix for three things - Is it Symmetric, Skew Symmetric, Singular Remember -

Symmetric is  𝐴𝑇=𝐴 
Skew Symmetric is  𝐴𝑇=−𝐴 
Singular is  det(𝐴)=0 
At this point, we already have the transposed values so its easy to check if all the matrices are Symmetric, Skew Symmetric or Singular. Since we have three matrices and we need to do the same thing on all three matrices, we are going to write a function to solve this problem.

In [3]:
# Starting with matrix A 
def check_matrices(mat): 
    mat_T = np.transpose(mat)
    
   
    sym_check =np.allclose(mat_T,mat) ## Check if mat and mat_T are array equal
    sksym_check =np.allclose(mat_T,-mat) ## Check if minus mat and mat_T are array equal
    singular_check =np.linalg.det(mat) ## Using the numpy linear algebra package, calcuate the determinant
    
    ## Write a dict called results wehre you store the answers based on the keys 
    ## symmetric, ske_skymmetric and singular  
    results ={"symmetric": sym_check,
             "skew_symmetric": sksym_check,
             "singular":singular_check}
    return results 


results_A  = check_matrices(A)
results_B = check_matrices(B)
results_C = check_matrices(C)

print("Results from check matrices for A: \n {}".format(results_A))
print("Results from check matrices for B: \n {}".format(results_B))
print("Results from check matrices for C: \n {}".format(results_C))

# Are A, B and C singular? 
singular_A = "Non singular"
singular_B = "Singular"
singular_C = "Singular"

print("A is {}, B is {}, C is {}".format(singular_A, singular_B, singular_C))

Results from check matrices for A: 
 {'symmetric': True, 'skew_symmetric': False, 'singular': -253159.99999999977}
Results from check matrices for B: 
 {'symmetric': False, 'skew_symmetric': False, 'singular': 0.0}
Results from check matrices for C: 
 {'symmetric': False, 'skew_symmetric': True, 'singular': 0.0}
A is Non singular, B is Singular, C is Singular


### Perform the following operations

In [4]:
# Add matrices A and B 
print("result of A + B is {}".format(A + B))


#The addition can not be done. Two matrices can be added, only if they have the same dimensions.

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [5]:
matmul_AC  =np.matmul(A,C) # matrix multiply matrices A and C using numpy 
print("matrix multiplication of A and C is : \n {}".format(matmul_AC))
 

matrix multiplication of A and C is : 
 [[-2570.   -630.4 10698.5]
 [-2370.   -206.7 25476. ]
 [-7554.  -2541.   2776.7]]
